[ shell ]
program = "/bin/zsh"
args = [ "-l", "-c", "tmuxinator work"]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.9
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14
