#! /bin/sh

$HOME/.config/bspwm/autostart.sh


bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width 5


bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config window_gap 10 

bspc rule -a feh state="floating" center=true
bspc rule -a feh border=off
bspc rule -a Eww border=off state="floating" desktop=2
bspc rule -a TelegramDesktop state="floating"
bspc rule -a copyq state="floating" center=true
