return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    event = { "BufReadPre", "BufNewFile" },
    build = ":TSUpdate",
    lazy = false,
    config = function()
      require("nvim-treesitter").setup({})

      require("nvim-treesitter").install({
        "go",
        "gomod",
        "gosum",
        "json",
        "javascript",
        "typescript",
        "tsx",
        "yaml",
        "toml",
        "html",
        "css",
        "scss",
        "markdown",
        "markdown_inline",
        "svelte",
        "vue",
        "graphql",
        "bash",
        "lua",
        "luadoc",
        "vim",
        "vimdoc",
        "dockerfile",
        "gitignore",
        "gitcommit",
        "diff",
        "query",
        "regex",
        "nix",
        "rust",
        "sql",
        "c",
        "cpp",
        "python",
        "kotlin",
        "java",
        "proto",
        "elixir",
      })
    end,
  },
  {
    "windwp/nvim-ts-autotag",
    event = "InsertEnter",
    opts = {},
  },
}
